freicalisite/freicalisite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('juroComposto.urls')),
    path('admin/', admin.site.urls),
]

freicalisite/juroComposto/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'juroComposto'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:igpm_id>/', views.detail, name='detail'),
    path('updateIgpm/<int:igpm_id>/', views.detail, name='updateIgpm'),

]

freicalisite/juroComposto/models.py
from django.db import models

# Create your models here.
from django.db import models


class igpm(models.Model):
    data = models.DateTimeField('data')
    taxa = models.DecimalField(max_digits=20, decimal_places=10)
    multiplicadorAbsoluto = models.DecimalField(max_digits=20, decimal_places=10)

freicalisite/juroComposto/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime

from .models import igpm
from django.template import loader
from django.shortcuts import get_object_or_404,render
from django.http import Http404
from django.urls import reverse
from decimal import Decimal

def list(request):
    latest_igpm_list = igpm.objects.order_by('-data')[:5]
    output = ', <BR>'.join([q.data.strftime("%B %Y") for q in latest_igpm_list])
    return HttpResponse(output)

def index(request):
    latest_igpm_list = igpm.objects.order_by('-data')[:5]
#    template = loader.get_template('juroComposto/index.html')
    context = {'latest_igpm_list': latest_igpm_list,}
 #   return HttpResponse(template.render(context, request))
    return render(request, 'juroComposto/index.html', context)

def detail(request, igpm_id):
    try:
        igpmt = igpm.objects.get(pk=igpm_id)
    except igpm.DoesNotExist:
        raise Http404("igpm does not exist")
    return render(request, 'juroComposto/detail.html', {'igpm': igpmt})

def updateIgpm(request, igpm_id):
    igpmt = get_object_or_404(igpm, pk=igpm_id)
    try:
        newTaxa = Decimal(request.POST['taxa'])
        print(request.POST['taxa'])
        print(newTaxa)
    except Exception as e:
        # Redisplay the question voting form.
        return render(request, 'juroComposto/detail.html', {
            'igpm': igpmt,
            'error_message': "Valor nao numerico",
        })
    else:
        igpmt.taxa = newTaxa
        igpmt.multiplicadorAbsoluto = 1 + (newTaxa/100)
        igpmt.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('juroComposto:index', args=(igpmt.id,)))

freicalisite/juroComposto/templates/juroComposto/detail.html
<h1>{{ igpm.data }}</h1>
<ul>
    <li>{{ igpm.taxa }}</li>
</ul>


<form action="{% url 'juroComposto:updateIgpm' igpm.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ igpm.data }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <input type="text" name="taxa" id="taxa" value="{{ igpm.taxa }}">
        <br>
</fieldset>
<input type="submit" value="update">
</form>

freicalisite/juroComposto/templates/juroComposto/index.html
{% if latest_igpm_list %}
    <ul>
    {% for igpm in latest_igpm_list %}
        <li><a href="{% url 'juroComposto:detail' igpm.id %}">{{ igpm.data }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No IGPM are available.</p>
{% endif %}